// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateInventoryInput struct {
	Name     string `json:"name"`
	Quantity int    `json:"quantity"`
	Type     string `json:"type"`
}

type CreateOrderInput struct {
	Customer string `json:"customer"`
	Product  string `json:"product"`
	Quantity int    `json:"quantity"`
	Status   string `json:"status"`
}

type CreateSaleInput struct {
	Product  string  `json:"product"`
	Quantity int     `json:"quantity"`
	Price    float64 `json:"price"`
	Date     string  `json:"date"`
}

type CreateWorkOrderInput struct {
	Task       string  `json:"task"`
	AssignedTo *string `json:"assignedTo,omitempty"`
	Status     string  `json:"status"`
}

type Mutation struct {
}

type Query struct {
}

type UpdateInventoryInput struct {
	Name     *string `json:"name,omitempty"`
	Quantity *int    `json:"quantity,omitempty"`
	Type     *string `json:"type,omitempty"`
}

type UpdateOrderInput struct {
	Customer *string `json:"customer,omitempty"`
	Product  *string `json:"product,omitempty"`
	Quantity *int    `json:"quantity,omitempty"`
	Status   *string `json:"status,omitempty"`
}

type UpdateSaleInput struct {
	Product  *string  `json:"product,omitempty"`
	Quantity *int     `json:"quantity,omitempty"`
	Price    *float64 `json:"price,omitempty"`
	Date     *string  `json:"date,omitempty"`
}

type UpdateWorkOrderInput struct {
	Task       *string `json:"task,omitempty"`
	AssignedTo *string `json:"assignedTo,omitempty"`
	Status     *string `json:"status,omitempty"`
}
